### ISSUE TITLE
spr 23 syllabus course objective seem out of sync with course content

### ISSUE THREAD

**Issue by sunwsusan** [stjohn/datasci#10]
https://stjohn.github.io/datasci/spr23/syl.html

At the bottom of the syllabus, the course objective states:
```
Course Objectives
At the end of the course, students should be able to:
- Acquire data sets from multiple sources and write programs that can extract (scrape) the data into a usable form.
- Use data mining to extract new insights about the data.
- Understand basic storage techniques and constraints.
- Analyze data using standard techniques from statistics and linear algebra.
- Visualize data using popular Python modules.
```

I'm not entirely sure the first objective matches the course content.  How much lecture time or coursework will be focused on data scraping?

**Comment by stjohn** [comment]
Yup, I agree.   Let's rewrite it-- also, do we want to add/subtract to topics?

**Comment by sunwsusan** [comment]
I have 2 suggestions.

1. I think we should align with the course description.  Copy pasted here:
```
Description: 3 hours, 3 credits: This topics course focuses on computational methods and statistical techniques to analyze 
data and make inferences. Topics include data collection and cleaning, exploratory data analysis and visualization, and 
statistical inference and prediction. Students will acquire a working knowledge of data science through hands-on projects 
with real-world data. Basic proficiency in statistics and Python programming is assumed, as well as experience with abstract 
data structures.
```

2. If we are to write this out in bullet points, we should give equal weighting to the topics equivalent to the time we spend on each objective.  For example, my attempt at this would probably have something like this
```
- one bullet point on data collection and cleaning
- one bullet point on EDA, visualization, and statistic inference
- one or two bullet points on predictive modeling / machine learning, supervised and non supervised
- one more bullet point on all else
```
How do you feel about the weighting?  I think a lot of the original course objectives could be kept as-is.  The biggest difference for me, is that I feel like the objectives did not give enough emphasis on ML.

Thoughts?

**Comment by stjohn** [comment]
That looks great!  

Random musing:  The book/our emphasis is more on predictive modeling than machine learning (in that we kinda don't say the words machine learning until 2/3 of the way through the class).  I kinda like that we don't make it all about ML, in that the department has a whole class on machine learning, and students tend to conflate data science with ML.  So, having it as half a bullet point seems good.

**Comment by sunwsusan** [comment]
Re: ML vs predictive modeling conflation above.  Agreed.

Draft v0.1:

```
Course Objectives
At the end of the course, students should be able to:
- Acquire data sets from multiple sources and write programs that can extract, transform, and load the data into a usable form.
- Use exploratory data analysis and visualization techniques as well as linear algebra and statistical inference to extract new insights from the data.
- Understand the theoretical concepts as well as the process and application of various predictive modeling techniques.
- Apply predictive modeling and machine learning techniques to medium to large data sets and interpret the results and assess goodness of fit.
```

Still not too happy w/ the last 2 bullet points, any tips?

**Comment by stjohn** [comment]
Looks so much better!

**Comment by stjohn** [comment]
For last 2:  do you want to reorganize/split into the doing (apply predictive modeling and ML to data sets) and the understanding (understand the theory & interpret results)?

**Comment by sunwsusan** [comment]
https://github.com/stjohn/datasci/pull/16
