### ISSUE TITLE
spr 23 office hour link redirecting to trees seminar 

### ISSUE THREAD

**Issue by sunwsusan** [stjohn/datasci#11]
Under spring 2023 csci 39542 coursework resources page (https://stjohn.github.io/datasci/spr23/resources.html), the hyperlink for "office hours" currently redirects to the contact info for trees seminar (https://stjohn.github.io/teaching/officeHours.html)

```
Office Hours & Contact Information
- Office hours (<- this hyperlink)
- The course email is: datasci AT hunter cuny edu
```

**Comment by stjohn** [comment]
Fixed.  Thank you!
