### ISSUE TITLE
spr 23 lecture 2 reading link broken

### ISSUE THREAD

**Issue by sunwsusan** [stjohn/datasci#13]
In the index page (https://stjohn.github.io/datasci/spr23/index.html), for lecture 2 `Wednesday, 1 February`, under the `Reading Column`, the hyperlink to [Guessing Correlation Coefficients](https://shiney.zoology.ubc.ca/whitlock/Guessing_correlation/) redirects to https://shiney.zoology.ubc.ca/whitlock/Guessing_correlation/, but the site times out after a few minutes and never loads.

**Comment by sunwsusan** [comment]
possible alternative: https://guessthecorrelation.com/ ?

**Comment by stjohn** [comment]
Oh no!  UBC is where the great sampling from distributions apps are.  Very relieved that all those seem to be working.  

The nice thing about the UBC one is that it generated 4 different possible answers and had students choose the best.  Did a quick google search and can't find any that do that, but how about this one:  https://www.geogebra.org/m/KE6JfuF9

**Comment by sunwsusan** [comment]
yup, tested out GeoGebra's version and I like it!  Updating it on the PR linked here.
